# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jackd/ECE194BB_Final/ECE194BB_Final.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_7/design_1_clk_wiz_7.xci
# IP: The module: 'design_1_clk_wiz_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jackd/ECE194BB_Final/ECE194BB_Final.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_7/design_1_clk_wiz_7_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jackd/ECE194BB_Final/ECE194BB_Final.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_7/design_1_clk_wiz_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jackd/ECE194BB_Final/ECE194BB_Final.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_7/design_1_clk_wiz_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/jackd/ECE194BB_Final/ECE194BB_Final.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_7/design_1_clk_wiz_7.xci
# IP: The module: 'design_1_clk_wiz_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jackd/ECE194BB_Final/ECE194BB_Final.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_7/design_1_clk_wiz_7_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jackd/ECE194BB_Final/ECE194BB_Final.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_7/design_1_clk_wiz_7.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/jackd/ECE194BB_Final/ECE194BB_Final.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_7/design_1_clk_wiz_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
